create table address
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street varchar(50)
);

create table client
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(50),
    address_id bigint references address
);

create table phone
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar(50),
    client bigint references client
);

insert into address(street)
values ('ул. Ленина');
insert into client(name, address_id)
values ('admin', 1);
insert into phone(number, client)
values ('+79876543210', 1);